// TRIKAL VAANI - Karmic Background Reading - Payment Verification API
// CEO: Rohiit Gupta
// File: app/api/verify-karmic-payment/route.ts
// VERSION: 1.0
// Per Strategic Plan v2.0 §4. Flat Rs251, single person.
//
// Mirrors verify-milan-payment, with ONE difference:
//   Karmic does NOT compute the chart here. It creates the karmic_readings
//   row (status paid) and returns the slug. The chart + 6-dimension reading
//   are generated by /api/karmic-reading (called by the result page).
//   This keeps payment verification fast and the heavy AI work separate.

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import crypto from 'crypto';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

interface KarmicVerifyRequest {
  razorpay_order_id:   string;
  razorpay_payment_id: string;
  razorpay_signature:  string;
}

function makeSlug(): string {
  const ts  = Date.now().toString(36);
  const rnd = crypto.randomBytes(4).toString('hex');
  return `k-${ts}-${rnd}`;
}

export async function POST(req: NextRequest) {
  try {
    const body: KarmicVerifyRequest = await req.json();
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = body;

    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return NextResponse.json({ error: 'Missing payment fields.' }, { status: 400 });
    }

    // Verify HMAC signature
    const secret   = process.env.RAZORPAY_KEY_SECRET!;
    const payload  = `${razorpay_order_id}|${razorpay_payment_id}`;
    const expected = crypto.createHmac('sha256', secret).update(payload).digest('hex');

    if (expected !== razorpay_signature) {
      console.error('[Trikal] Karmic signature mismatch:', razorpay_order_id);
      return NextResponse.json({ error: 'Payment verification failed.' }, { status: 400 });
    }

    // Load the pending order
    const { data: order, error: orderErr } = await supabase
      .from('karmic_orders')
      .select('*')
      .eq('razorpay_order_id', razorpay_order_id)
      .single();

    if (orderErr || !order) {
      console.error('[Trikal] Karmic order not found:', razorpay_order_id, orderErr?.message);
      return NextResponse.json({ error: 'Order not found.' }, { status: 404 });
    }

    // Idempotency replay — if already verified, return existing reading slug
    if (order.payment_verified === true) {
      const { data: existing } = await supabase
        .from('karmic_readings')
        .select('slug')
        .eq('order_id', order.id)
        .maybeSingle();
      if (existing?.slug) {
        return NextResponse.json({
          success: true, slug: existing.slug, paymentId: razorpay_payment_id,
          resultUrl: `https://trikalvaani.com/karmic/${existing.slug}`, replay: true,
        });
      }
    }

    // Mark order paid
    await supabase
      .from('karmic_orders')
      .update({
        razorpay_payment_id, razorpay_signature,
        status: 'paid', payment_verified: true, paid_at: new Date().toISOString(),
      })
      .eq('id', order.id);

    // Create the reading row (chart + narrative generated later by /api/karmic-reading)
    const slug = makeSlug();

    const { error: saveErr } = await supabase
      .from('karmic_readings')
      .insert({
        order_id:          order.id,
        slug,
        language:          order.language,
        person_data:       order.person_data,
        kundali_data:      null,
        dimensions_data:   null,
        gemini_narrative:  null,
        geo_answer:        null,
        source_milan_slug: order.source_milan_slug ?? null,
        pdf_url:           null,
        is_public:         false,
      });

    if (saveErr) {
      console.error('[Trikal] Karmic reading row save error:', saveErr.message);
      return NextResponse.json({
        success: true, paymentId: razorpay_payment_id,
        warning: 'Payment received. Reading is being prepared — please contact us if the result page does not load.',
      }, { status: 200 });
    }

    const personName = (order.person_data?.name ?? '').toString();

    const waText = encodeURIComponent(
      `Jai Mahakaal! Trikal Vaani Karmic Background Reading confirm ho gaya.\n\n` +
      `Reading for: ${personName}\n` +
      `Payment ID: ${razorpay_payment_id}\n` +
      `Result: trikalvaani.com/karmic/${slug}\n\nJai Maa Shakti!`
    );

    return NextResponse.json({
      success:     true,
      slug,
      language:    order.language,
      paymentId:   razorpay_payment_id,
      amount:      order.amount_rupees,
      resultUrl:   `https://trikalvaani.com/karmic/${slug}`,
      whatsappUrl: `https://wa.me/919211804111?text=${waText}`,
    });

  } catch (err: unknown) {
    console.error('[Trikal] Verify Karmic payment error:', err);
    return NextResponse.json({ error: 'Server error during verification.' }, { status: 500 });
  }
}
